services:
  - type: web
    name: orcode-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PISTON_API_URL
        value: https://orcode-piston.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: web
    name: orcode-piston
    env: docker
    dockerfilePath: ./piston/Dockerfile
    dockerContext: ./piston
    envVars:
      - key: PISTON_LOG_LEVEL
        value: INFO