services:
  - type: web
    name: orcode-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PISTON_API_URL
        value: http://piston:2000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: pserv
    name: piston
    env: docker
    dockerfilePath: ./piston/Dockerfile
    dockerContext: ./piston
    envVars:
      - key: PISTON_LOG_LEVEL
        value: INFO